[package]
name = "crabby"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
octocrab = "0.29.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
